# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Velos_config = debug
  Example_Triangle_config = debug

else ifeq ($(config),release)
  Velos_config = release
  Example_Triangle_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Velos Example_Triangle

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Velos:
ifneq (,$(Velos_config))
	@echo "==== Building Velos ($(Velos_config)) ===="
	@${MAKE} --no-print-directory -C build/Velos -f Makefile config=$(Velos_config)
endif

Example_Triangle: Velos
ifneq (,$(Example_Triangle_config))
	@echo "==== Building Example_Triangle ($(Example_Triangle_config)) ===="
	@${MAKE} --no-print-directory -C build/Example_Triangle -f Makefile config=$(Example_Triangle_config)
endif

clean:
	@${MAKE} --no-print-directory -C build/Velos -f Makefile clean
	@${MAKE} --no-print-directory -C build/Example_Triangle -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Velos"
	@echo "   Example_Triangle"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"