#version 460
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 4, local_size_y = 4, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D globalTextures[];
layout(set = 0, binding = 1, rgba8) uniform writeonly image2D outputImage;

layout(push_constant) uniform DrawData {
    uint leftTextureIndex;
    uint rightTextureIndex;
} drawData;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = (vec2(pixel) + vec2(0.5)) / vec2(imageSize(outputImage));
    uint textureIndex = pixel.x < imageSize(outputImage).x / 2
        ? drawData.leftTextureIndex
        : drawData.rightTextureIndex;
    vec4 color = texture(
        globalTextures[nonuniformEXT(textureIndex)], uv);
    imageStore(outputImage, pixel, color);
}
