#version 450

layout(local_size_x = 4, local_size_y = 4, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2D sourceTexture;
layout(set = 0, binding = 1, rgba8) uniform writeonly image2D destinationImage;

void main() {
  ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
  vec2 size = vec2(imageSize(destinationImage));
  vec2 uv = (vec2(pixel) + vec2(0.5)) / size;
  imageStore(destinationImage, pixel, textureLod(sourceTexture, uv, 0.0));
}
