#version 450

layout(local_size_x = 4, local_size_y = 4, local_size_z = 1) in;
layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outputImage;

void main() {
  ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
  imageStore(outputImage, pixel, vec4(
      float(uint(pixel.x) * 31u + 5u) / 255.0,
      float(uint(pixel.y) * 43u + 9u) / 255.0,
      float((uint(pixel.x) + uint(pixel.y)) * 17u + 13u) / 255.0,
      1.0));
}
