#version 460

layout(local_size_x = 4, local_size_y = 4, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outputImage;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    imageStore(outputImage, pixel, vec4(
        float(pixel.x * 23 + 11) / 255.0,
        float(pixel.y * 17 + 19) / 255.0,
        float((pixel.x + pixel.y) * 13 + 7) / 255.0,
        1.0));
}
